# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CNN_imp/CNN_imp.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNN_imp || ORIG_REF_NAME==CNN_imp} -quiet] -quiet

# IP: bd/CNN_imp/ip/CNN_imp_axi_dma_0_0/CNN_imp_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNN_imp_axi_dma_0_0 || ORIG_REF_NAME==CNN_imp_axi_dma_0_0} -quiet] -quiet

# IP: bd/CNN_imp/ip/CNN_imp_axi_smc_0/CNN_imp_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNN_imp_axi_smc_0 || ORIG_REF_NAME==CNN_imp_axi_smc_0} -quiet] -quiet

# IP: bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNN_imp_rst_ps7_0_100M_0 || ORIG_REF_NAME==CNN_imp_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/CNN_imp/ip/CNN_imp_ps7_0_axi_periph_0/CNN_imp_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNN_imp_ps7_0_axi_periph_0 || ORIG_REF_NAME==CNN_imp_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CNN_imp/ip/CNN_imp_zynq_ultra_ps_e_0_3/CNN_imp_zynq_ultra_ps_e_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNN_imp_zynq_ultra_ps_e_0_3 || ORIG_REF_NAME==CNN_imp_zynq_ultra_ps_e_0_3} -quiet] -quiet

# IP: bd/CNN_imp/ip/CNN_imp_auto_pc_0/CNN_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNN_imp_auto_pc_0 || ORIG_REF_NAME==CNN_imp_auto_pc_0} -quiet] -quiet

# IP: bd/CNN_imp/ip/CNN_imp_mlp_0_2/CNN_imp_mlp_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CNN_imp_mlp_0_2 || ORIG_REF_NAME==CNN_imp_mlp_0_2} -quiet] -quiet

# XDC: bd/CNN_imp/CNN_imp_ooc.xdc
