# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0.xci
# IP: The module: 'CNN_imp_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0.xci
# IP: The module: 'CNN_imp_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_rst_ps7_0_100M_0/CNN_imp_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
