# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_zynq_ultra_ps_e_0_3/CNN_imp_zynq_ultra_ps_e_0_3.xci
# IP: The module: 'CNN_imp_zynq_ultra_ps_e_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_zynq_ultra_ps_e_0_3/CNN_imp_zynq_ultra_ps_e_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_zynq_ultra_ps_e_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_zynq_ultra_ps_e_0_3/CNN_imp_zynq_ultra_ps_e_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_zynq_ultra_ps_e_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_zynq_ultra_ps_e_0_3/CNN_imp_zynq_ultra_ps_e_0_3.xci
# IP: The module: 'CNN_imp_zynq_ultra_ps_e_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_zynq_ultra_ps_e_0_3/CNN_imp_zynq_ultra_ps_e_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_zynq_ultra_ps_e_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/CNNproj/Ultra96/FPGA/Vivado_synthesis/Vivado_implementation.srcs/sources_1/bd/CNN_imp/ip/CNN_imp_zynq_ultra_ps_e_0_3/CNN_imp_zynq_ultra_ps_e_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'CNN_imp_zynq_ultra_ps_e_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
